PATTERN_MAP = {
    "砂岩": "sandstone",
    "泥岩": "mudstone",
    "灰岩": "limestone",
    "白云岩": "dolomite",
    "页岩": "shale",
    "粉砂岩": "siltstone",
    "砂坪": "sand-flat",
    "泥坪": "mud-flat",
    "云质坪": "dolomitic-flat",
    "混积潮坪": "dolomitic-flat",
    "碎屑岩潮坪": "tidal-flat",
    "潮坪": "tidal-flat",
    "泥质陆棚": "muddy-shelf",
    "砂质陆棚": "sandy-shelf",
    "砂泥质陆棚": "sand-mud-shelf",
    "碎屑岩浅水陆棚": "clastic-shelf",
    "混积浅水陆棚": "mixed",
    "陆棚": "shelf",
    "混积": "mixed",
    "三角洲": "delta",
}

FACIES_COLORS = {
    "砂岩": "#f0d9b5",
    "泥岩": "#d4c5a9",
    "灰岩": "#b5d4c1",
    "白云岩": "#a8cdb8",
    "页岩": "#c9bfa0",
    "粉砂岩": "#e6c9a8",
    "砂坪": "#f0d9b5",
    "泥坪": "#d4c5a9",
    "云质坪": "#c4d4c0",
    "混积潮坪": "#c4d4c0",
    "碎屑岩潮坪": "#d4c5a9",
    "潮坪": "#d4c5a9",
    "泥质陆棚": "#d4c5a9",
    "砂质陆棚": "#f0d9b5",
    "砂泥质陆棚": "#dccfb5",
    "碎屑岩浅水陆棚": "#d4c5a9",
    "混积浅水陆棚": "#c4d4c0",
    "陆棚": "#d9d4c8",
    "混积": "#c4d4c0",
    "三角洲": "#e6c9a8",
    "深水盆地": "#9bb5cf",
    "碳酸盐台地": "#b5d4c1",
}
